### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by AlAyoub** [SheetJS/voc#5]
Thank you @SheetJSDev for merging the Marked.js 0.8.0 upgrade. I believe there needs to be a version bump for npm to see the change, is that right? If so, please bump the version and thank you again!

**Comment by SheetJSDev** [comment]
1.2.0

**Comment by AlAyoub** [comment]
@SheetJSDev 1.2.0 resolved our security issue, thank you again for merging and version bumping!
